---
title: "Physician Agency, Training, and Location"
author: "Ian McCarthy | Emory University"
format: 
  revealjs:
    theme: [moon]
    preview-links: auto
    chalkboard:
      boardmarker-width: 5
    slide-number: true
    width: 1600
    height: 900    
#    embed-resources: true
from: markdown+emoji
execute: 
  echo: true
---

```{r}
#| include: false
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, lubridate, gapminder, scales)
```

# Variation in Health Care

---

## Variation in Health Care

Consequences of physician agency:

- Patients subjected to information frictions or financial incentives of physicians
- The types of care people receive will depend on the physician
- Potential variation in health care utilization and spending across and even within markets

---

## Variation in Health Care

Consequences of physician agency:

- Patients subjected to [information frictions]{.underline} or financial incentives of physicians
- The types of care people receive will depend on the physician
- Potential variation in health care utilization and spending across and even within markets

---

## Information frictions

- Physicians don't all have the exact same information
- May depend on...
  - Learning over time (exposure to different patients and different treatment options)
  - **Training and Location** (peers)
  - Ownership structure (employee of hospital, large group, or self-employed)
  
  
# Physician Training

---

## Areas of "training"

- Medical education
- Choice of specialization
- Personal biases (not really training, but important nonetheless)

---

## Examples

- Team effects and influence during residency (Chan, 2021)
- Physicians following treatment patterns of advisors in residency [(Pany, 2023)](https://ashecon.confex.com/ashecon/2023/meetingapp.cgi/Paper/14080)
- PCP training associated with less healthcare utilization (Kravitz and Greenfield, 1995)


# Physician Location and Practice

---

## Peer effects

- Peer effects pervasive in many areas
- Do they apply to physicians in terms of their treatment decisions?
- Physicians adopting practice patterns of peers in new practice (Molitor, 2018)


---

## Molitor (2018)

- **The evolution of physician practice styles: evidence from cardiologist migration**
- Study cardiologist practice styles upon joining new practices (physician movers)
- Practice environment can explain 60-80% of "supply-side" variation, at least in cardiology

---

## Badinski, et al. (2023)

- **Geographic Variation in Healthcare Utilization: The Role of Physicians**
- New work effectively combining lots of prior approaches into one coherent study
- Illustrates significant heterogeneities across types of physicians
- For cardiologists:
  - Practice environment a major factor
  - Individual physician practice style less relevant
- For PCPs:
  - Practice environment less critical
  - Individual physician practice style more important (explains around 20% of observed variation)
  

# Who cares?

---

## The problem

- Significant variation in healthcare utilization across and within markets 
- Not explained by patient need or quality of care
- Points to clear inefficiencies (can reduce utilization without sacrificing quality)

---

## Sources of inefficiency


- Learning and information
- Practice environment and peer effects
- Physician training and prior beliefs

---

## Potential solutions

- Information transparency (FDA, rating systems, etc.)
- Opportunity for spillovers, but changing practice patterns is hard
  - Checklists, EHRs, etc.
  - Physicians don't always like them

