---
title: "Public Health Insurance"
author: "Ian McCarthy | Emory University"
format: 
  revealjs:
    theme: [moon]
    preview-links: auto
    chalkboard:
      boardmarker-width: 5
#    embed-resources: true
from: markdown+emoji
execute: 
  echo: true
---

```{r}
#| include: false
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, lubridate, gapminder, scales)
```

# Table of contents

1. Medicare
2. Medicaid
3. Veterans Administration


# Medicare

---

## Basics of Medicare

- Created by the Social Security Act in 1965
- Originally health insurance to those 65 years of age and older
- Expanded to include certain disabilities (20% now below age 65)

---

Medicare consists of four parts:

  - Part A: Hospital Insurance
  - Part B: "Medical" Insurance (physician visits and outpatient care)
  - Part C: Private supplemental care (Medicare plus Choice, now Medicare Advantage)
  - Part D: Prescription Drug Coverage

---

## Medicare Part A

- Automatic enrollment for anyone 65 and older who worked over their lifetime
- Financed with combination of payroll tax (current workers) and cost-sharing (deductibles, etc.)
- Funds exist as part of "Federal Hospital Insurance Trust Fund"...can't finance through debt

---

Part A benefit structure:

  - Very good for short inpatient stays
  - Very bad for major problems with long stays
  - Doesn't cover nursing home care beyond 30 days

---

## Medicare Part B

- Voluntary, but almost everyone enrolls
- Requires monthly premium ($144 in 2020)
- Small deductible and 20% co-insurance


---

## Medicare Part C

- Private insurance provision of Medicare benefits
- Formally created under Balanced Budget Act in 1997 (existed informally before)
- Heavily revised in Medicare Modernization Act in 2003
- Medicare pays insurers a risk-adjusted amount to enroll a given beneficiary
- Broader benefits than Part A and B, often with $0 additional premiums, but restrictive networks

---

## Medicare Part D

- Created under the Medicare Modernization Act in 2003
- Private insurance for prescription drugs
- Insurers receive payments from Medicare to enroll a given beneificiary (much like Part C)
- Many insurers offer a combined Part C+D plan

---

## Privatization of Medicare

- Medicare Advantage (both Parts C and D) has been well-received and generally thought to be a success story for Medicare benefits
- Accounts for nearly **half** of total Medicare enrollees
- Some early difficulties with adverse selection and risk-adjustment
- Still slightly sicker people staying in traditional Medicare
- Could be a <b>big</b> part of any future "Medicare-for-all" type program

---

## Medicare payments for inpatient services

- Prospective payment system
- Begin with two "base" rates:
  - Operating base payment rates, \$5,797 in 2020
  - Capital base payment rates, \$462 in 2020
- Adjustments:
  - Diagnosis Related Group (higher adjustments for more complicated things)
  - Academic Medical Center
  - Disproportionate Share

---

More recently:

- Introduction of quality incentives through...
  - Value Based Purchasing (VBP)
  - Hospital Readmission Reduction Program (HRRP)
  - Quality Payment Program for physicians (choose between merit based payment system or advanced alternative payment models)
- Introduction of capitated payments through...
  - Bundled Payments
  - Accountable Care Organizations

# Medicaid

---

## Background on Medicaid

- Also created by the Social Security Act in 1965
- Originally provided health insurance to people receiving "Aid to Families with Dependent Children", mainly extremely poor families
- Expanded over time with different rules by state
- Huge program: about 40% of births are covered by Medicaid/CHIP

---

## ACA and Medicaid Expansion

- Big part of ACA was Medicaid expansion
- Originally mandatory but made voluntary by Supreme Court
- Expansion covers all adults (with or without children) below age 65 and with incomes below 138% of the federal poverty line ($35,535 for family of 4 in 2020)
  
---

## Medicaid Funding

- Paid for by states and federal funding
- State funding is matched by federal funds, and the match amount depends on the state's per capita income
- Incentivizes services to be provided by Medicaid that historically may not be

---

## Medicaid Benefits

- Pretty generous coverage
- Low to no copayments, deductibles, co-insurance
- Usually covers dental, vision, hospitals, and physician services
- Covers long term care (unlike Medicare), with about 40% of all long term care paid for by Medicaid

---

## Medicaid Payments

- Works similarly to Medicare with a base rate plus adjustments
- Base rates vary by state Medicaid agencies
- Adjustments (or supplemental payments) consist of:
  - Disproportionate share adjustments 
  - Other (non-DSH) adjustments
  - Account for a little less than half of total Medicaid payments on average

---

## Privatization in Medicaid

- Increasing reliance on Medicaid managed care (80% of Medicaid enrollees)
- States outsource Medicaid benefits to private insurers, with oversight

# Veterans Administration

---

- "Integrated" healthcare provider and insurer
- Comprehensive medical services without out-of-pocket payments or insurance claims
- Operates its own healthcare facilities and employs healthcare providers directly, covering the costs of care provided to veterans
- Funding for VA healthcare comes from the federal government's budget allocated to the VA, which covers staffing, facilities, equipment, medications, and other necessary resources for delivering healthcare services to veterans
